### ISSUE TITLE
画师名称的正则式匹配可能会让文件夹名称为空而导致创建失败

### ISSUE THREAD

**Issue by Cardidi** [miracleXL/scripts-for-Eagle#1]
默认情况下的正则式会自动的对画师的名称修饰符号进行清除，但是遇到类似此画师（[☆](https://www.pixiv.net/users/21051287)）的情况时，文件夹名称变为空字符串，Eagle也将无法生成文件夹，从而导致整个导出被中断。修改正则式虽然可以避免这种问题发生，但是我建议最好在创建文件夹之前检查画师名称是否为空，就算为空也不要中断导出，而是提示用户该画师导出有问题，避免大量导出被中断。

**Comment by miracleXL** [comment]
谢谢提醒。早期代码写太乱了，有好几处复制粘贴的，这个问题我之前改过，没注意到漏掉了两处，已经改了。
