### ISSUE TITLE
添加自定义作者文件夹的功能

### ISSUE THREAD

**Issue by juzijun233** [miracleXL/scripts-for-Eagle#4]
目前脚本是直接在父目录下以画师名来建立
希望能增加一个自定义这个文件夹的功能，比如`画师ID_画师名`这样的格式支持

以及，发现接稿中的画师，会把接稿中一起获取到画师名中，不知道能否改善？

**Comment by miracleXL** [comment]
抱歉，最近太忙了没时间维护。“接稿中”这个问题我之前已经注意到了，试着更新过一次，但是马上就发现有bug又回退了回去。等忙完这段我再一起看看，感谢反馈

**Comment by miracleXL** [comment]
现在可以在设置里最后一行格式化里添加`${pid}_${authorName}`来实现了
