### ISSUE TITLE
无法下载gif图

### ISSUE THREAD

**Issue by juzijun233** [miracleXL/scripts-for-Eagle#7]
如题，下载gif图提示下载失败

**Comment by miracleXL** [comment]
从一开始就没实现这个功能，p站存的是zip的压缩文件，我不会转换格式，所以那部分代码是直接留空报了个错

**Comment by miracleXL** [comment]
另外我今天忙完就有空了，其他几个问题我明天改

**Comment by miracleXL** [comment]
计划有变，论文还要改，容我再鸽两个星期……

> 另外我今天忙完就有空了，其他几个问题我明天改
